name: cm_ratio
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy>=0.17.0
  - gdal>=3.0.4
  - jupyter>=1.0.0
  - matplotlib>=3.2.0
  - netcdf4>=1.5.3
  - numpy>=1.18.1
  - pyproj>=2.5.0
  - python>=3.8.2
  - xarray>=0.15.0
